### ISSUE TITLE
No título do site, ao lado do favicon, colocar “Bruto Valley | Comunidade de startups de Barretos”

### ISSUE THREAD

**Issue by niksonleonard** [brutovalley/site#2]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/1129223/129453374-593de25c-39fe-4bc0-b9ee-ce9c3ad7d334.png">

**Comment by attiquetecnologia** [comment]
tem como usar o firebase conecatdo ao github?

**Comment by niksonleonard** [comment]
@attiquetecnologia tem sim. É possível fazer Build e Deploy automaticamente usando o GitHub Actions. Quer que eu configure?
